# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'enciendeApp' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for enciendeApp
    source 'https://github.com/CocoaPods/Specs.git'
    pod 'React', :subspecs => ['Core', 'RCTImage', 'RCTNetwork', 'RCTText', 'RCTWebSocket'], :path => '../node_modules/react-native'
    pod 'react-native-fbsdkcore', :path => '../node_modules/react-native-fbsdk/iOS/core'
    pod 'react-native-fbsdklogin', :path => '../node_modules/react-native-fbsdk/iOS/login'
    pod 'react-native-fbsdkshare', :path => '../node_modules/react-native-fbsdk/iOS/share'
  target 'enciendeAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
